name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.2.8
  AWS_REGION: ap-northeast-1

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Debug check role ARN
        run: |
          if [ "${{ secrets.AWS_IAM_ROLE_ARN }}" = "arn:aws:iam::633442604392:role/tastylog-dev-githubations-iam-role" ]; then
            echo "MATCH: true"
          else
            echo "MATCH: false"
          fi
      - name: Checkout repository 
        uses: actions/checkout@v7
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform format
        run: |
          terraform fmt -check -recursive
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform init
        run: terraform init -no-color
